include: 
  - /meta
  #- /cmds # DO NOT INCLUDE YET! Krafter will include once it's ready
remote_theme: RoseSMP/clean
plugins:
  - jekyll-remote-theme
gems:
  - jekyll-index-pages
# the following is just a test.
index_pages:
  posts:
    title: Post Listing Page Title
    excerpt: Post listing page excerpt
    per_page: 20
    permalink: /blog
    layout: blog